CREATE TABLE USERS (
    UserID INT PRIMARY KEY AUTO_INCREMENT,
    UserNickName VARCHAR(15) NOT NULL,
    UserMail VARCHAR(20) NOT NULL,
    UserName VARCHAR(15) NOT NULL,
    UserSurname VARCHAR(15) NOT NULL,
    City VARCHAR(15)
);